name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
        - name: SSH deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST_DNS }}
            username:  ${{ secrets.USERNAME }}
            key:  ${{ secrets.EC2_SSH_KEY }}
            port:  ${{ secrets.PORT }}
            script: |
                sudo yum install -y gcc-c++ make
                curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
                sudo yum install -y nodejs
                sudo yum install -y git
                git clone https://github.com/sam-meech-ward-bcit/lotr
                cd lotr/
                npm i
                node server.js
